### ISSUE TITLE
#Issue

### ISSUE THREAD

**Issue by Vectormike** [Edmund1645/God-when-bot#2]
I'm not sure stream still works

https://github.com/Edmund1645/God-when-bot/blob/f47299b2d7d5f990cec66fd141d8fe1047dccb82/index.js#L11

**Comment by Edmund1645** [comment]
really? How so?

Update: I checked the docs, it still works. I think Twitter API might be buggy.

**Comment by Vectormike** [comment]
Oh, I checked too and they say its deprecated or something.

**Comment by Edmund1645** [comment]
Where? Mind sharing a link?

**Comment by Edmund1645** [comment]
I see the issue now, check this out: https://github.com/ttezel/twit/issues/44

I did this for the old bot, I thought that it just didn't make sense why I needed to include username to reply again. Turns out Twitter's API really is buggy.

**Comment by Vectormike** [comment]
So, it works now?
Sorry I slept off jare

**Comment by Edmund1645** [comment]
Yeah it does, check the `index.js` file, i also did some validation to ensure it doesn't reply the wrong tweets.
